custom_splitter:
  path:
  - './testdoc'
  chunk_size: 1024

pdf_ingestion:
  path: 
  - './testdoc'

embeddings:
  name: 
  - "nickprock/sentence-bert-base-italian-uncased"

similarity_metrics:
  - cosine
  - jaccard
  - euclidean

table_extraction:
  method: tabula
  parameters:
    flavor: lattice
    strip_text: "\n"
    
filters:
  file_size:
    min: 100
    max: 5000

  file_type:
    - pdf
    - docx


vector_store:
  path:
  -  "./VectorStore"
  name:
  -  "test1_collection" 
