custom_splitter:
  path:
  - '/home/giacomo/Documenti/GitHub/RAG-with-LLamaIndex-Open/testdoc'
  chunk_size: 1024

pdf_ingestion:
  path: 
  - '/home/giacomo/Documenti/GitHub/RAG-with-LLamaIndex-Open/testdoc'

embeddings:
  name: 
  - "nickprock/sentence-bert-base-italian-uncased"
  - "intfloat/multilingual-e5-large-instruct"
  max_length: 512

llm:
  path:
  - "/home/giacomo/Documenti/GitHub/RAG-with-LLamaIndex-Open/rag_open_source/model/mistral-Ita-7b-q5_k_m.gguf"

similarity_metrics:
  - cosine
  - jaccard
  - euclidean

table_extraction:
  method: tabula
  parameters:
    flavor: lattice
    strip_text: "\n"
    
filters:
  file_size:
    min: 100
    max: 5000

  file_type:
    - pdf
    - docx


vector_store:
  path:
  -  "./database"
  name:
  -  "test1_collection" 
  -  "multilingual_test_collection"
